#create resource group
resource "azurerm_resource_group" "longb_rg" {
  name     = "longb_terraform_rg"
  location = "UK South"
}

/* The private key generated by this resource will be stored unencrypted 
in your Terraform state file. Use of this resource for production deployments 
s not recommended. Instead, generate a private key file outside of Terraform 
and distribute it securely to the system where Terraform will be run. */
resource "tls_private_key" "private-key-example" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "local_file" "private_key" {
  content  = tls_private_key.private-key-example.private_key_pem
  filename = "${var.privatekeyname}.pem"
}
